const { createClient } = require('@supabase/supabase-js');

// Using service role key would be ideal, but we'll use anon key with super_admin context
// The insert will use a hardcoded owner_id from the profiles table
const supabase = createClient(
  'https://nwvarvvyhjkvtgijwfkc.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53dmFydnZ5aGprdnRnaWp3ZmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3NzU1NzQsImV4cCI6MjA5MDM1MTU3NH0.86IqiMJHcFWva9a0RUDKh_YEBo6Ynygt_BIvIov9gK4'
);

async function main() {
  // First, sign in as super admin to get auth context
  console.log('Signing in as super admin...');
  const { data: authData, error: authError } = await supabase.auth.signInWithPassword({
    email: 'invirtualcoin@gmail.com',
    password: process.argv[2] || ''
  });

  if (authError) {
    console.error('Auth error:', authError.message);
    console.log('\nTrying to get owner_id from profiles directly...');
    
    // Try to get super_admin profile ID using public read
    const { data: profiles, error: profileErr } = await supabase
      .from('profiles')
      .select('id, role')
      .eq('role', 'super_admin')
      .limit(1);
    
    if (profileErr) {
      console.error('Profile fetch error:', profileErr.message);
      return;
    }
    console.log('Found profiles:', profiles);
    return;
  }

  const ownerId = authData.user.id;
  console.log('Signed in. Owner ID:', ownerId);

  const grounds = [
    {
      name: 'Ambala Cricket Ground',
      description: 'Professional cricket ground for league and practice matches.',
      address: 'Ambala, Haryana',
      city: 'Ambala',
      state: 'Haryana',
      pincode: '133001',
      latitude: 30.3752,
      longitude: 76.7821,
      base_price_per_hour: 1200,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: true,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'DPGITM Sports Complex',
      description: 'Sports complex with outdoor cricket facilities.',
      address: 'DPGITM Campus, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122006',
      latitude: 28.4089,
      longitude: 76.9726,
      base_price_per_hour: 900,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: false,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Hare Knoll Cricket Ground',
      description: 'Premium cricket ground in Sector 72.',
      address: 'Sector 72, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122101',
      latitude: 28.4200,
      longitude: 77.0620,
      base_price_per_hour: 1100,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: true,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Worldplex Sports Ground',
      description: 'Multi-sport facility with top-notch cricket turf.',
      address: 'Worldplex, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122016',
      latitude: 28.4597,
      longitude: 77.0898,
      base_price_per_hour: 1050,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: false,
      has_pavilion: true,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Sturgeon Rain Barn Cricket Ground',
      description: 'Outdoor turf with pavilion for team events.',
      address: 'Chlorum, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122001',
      latitude: 28.4700,
      longitude: 77.0300,
      base_price_per_hour: 1150,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: true,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Ilog Sports Cricket Ground',
      description: 'Popular cricket ground near CSBT Road.',
      address: 'CSBT Road, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122006',
      latitude: 28.4800,
      longitude: 77.0550,
      base_price_per_hour: 1000,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: false,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Academy Sound Cricket Ground',
      description: 'Well-maintained cricket ground for all formats.',
      address: 'Academy Road, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122002',
      latitude: 28.4620,
      longitude: 77.0720,
      base_price_per_hour: 950,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: false,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: false,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Boundary Box Cricket Arena',
      description: 'Indoor box cricket with premium turf and lighting.',
      address: 'Boundary Complex, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122018',
      latitude: 28.4500,
      longitude: 77.0400,
      base_price_per_hour: 800,
      pitch_type: 'Box Cricket',
      ground_size: 'Box',
      capacity: 6,
      has_floodlights: false,
      has_parking: false,
      has_changing_rooms: true,
      has_pavilion: false,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Blue Parlor Box Cricket',
      description: 'Indoor box cricket near Bellowfarm area.',
      address: 'Bellowfarm Road, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122003',
      latitude: 28.4900,
      longitude: 77.0150,
      base_price_per_hour: 750,
      pitch_type: 'Box Cricket',
      ground_size: 'Box',
      capacity: 6,
      has_floodlights: false,
      has_parking: false,
      has_changing_rooms: true,
      has_pavilion: true,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Sun Tags Cricket Ground',
      description: 'Open-air cricket facility for evening matches.',
      address: 'Sector S3, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122051',
      latitude: 28.4650,
      longitude: 76.9800,
      base_price_per_hour: 1080,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: false,
      has_pavilion: true,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Strike Ani Strike Cricket Ground',
      description: 'Full-size turf ground for tournaments and league play.',
      address: 'Strike Complex, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122022',
      latitude: 28.4958,
      longitude: 77.0402,
      base_price_per_hour: 1200,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: true,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'JetStar Cricket Ground',
      description: 'Spacious ground with parking and changing rooms.',
      address: 'JetStar Complex, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122001',
      latitude: 28.4595,
      longitude: 77.0266,
      base_price_per_hour: 1150,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: false,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'CHC Town Cricket Ground',
      description: 'Cricket ground in Bengaluru with full facilities.',
      address: 'CHC Town, Bengaluru',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9716,
      longitude: 77.5946,
      base_price_per_hour: 1300,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: true,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'India Agencia Sports Ground',
      description: 'Well-equipped sports ground near Bengaluru centre.',
      address: 'India Agencia, Bengaluru',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560002',
      latitude: 12.9720,
      longitude: 77.5950,
      base_price_per_hour: 1100,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: false,
      has_pavilion: true,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Bells Of DunDablian Box Cricket',
      description: 'Indoor box cricket in DunDablian area.',
      address: 'DunDablian Road, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122004',
      latitude: 28.4700,
      longitude: 77.0600,
      base_price_per_hour: 780,
      pitch_type: 'Box Cricket',
      ground_size: 'Box',
      capacity: 6,
      has_floodlights: false,
      has_parking: false,
      has_changing_rooms: true,
      has_pavilion: false,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Kraft DrinkPole Star Cricket Ground',
      description: 'Premium cricket facility with floodlights.',
      address: 'Pole Star, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122009',
      latitude: 28.4850,
      longitude: 77.0850,
      base_price_per_hour: 1050,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: false,
      verified: true,
      approved: true,
      active: true,
    },
    {
      name: 'Staffora Caresema Cricket Ground',
      description: 'Ground with pavilion for league and friendly matches.',
      address: 'Caresema, Gurugram',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122007',
      latitude: 28.4400,
      longitude: 77.0200,
      base_price_per_hour: 990,
      pitch_type: 'Cricket Ground',
      ground_size: 'Standard',
      capacity: 22,
      has_floodlights: true,
      has_parking: true,
      has_changing_rooms: true,
      has_pavilion: true,
      verified: true,
      approved: true,
      active: true,
    },
  ];

  // Add owner_id to each ground
  const groundsWithOwner = grounds.map(g => ({ ...g, owner_id: ownerId }));

  console.log(`\nInserting ${groundsWithOwner.length} grounds...`);
  const { data, error } = await supabase
    .from('grounds')
    .insert(groundsWithOwner)
    .select('id, name');

  if (error) {
    console.error('Insert error:', error.message);
    console.error('Details:', error.details);
  } else {
    console.log(`\n✅ Successfully inserted ${data.length} grounds:`);
    data.forEach(g => console.log(`  - ${g.name} (${g.id})`));
  }

  await supabase.auth.signOut();
}

main().catch(console.error);
