import { StyleSheet, Platform } from 'react-native';
const styles = StyleSheet.create({
  modalHeaderPremium: {
    padding: 24,
    paddingTop: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitlePremium: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  modalSubtitlePremium: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.8)',
    marginTop: 2,
  },
  closeBtnPremium: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoCardPremium: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  infoCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  infoCardTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#01b854',
    letterSpacing: 1,
  },
  matchTeamsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  matchTeamItem: {
    flex: 1,
  },
  matchTeamName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#06392e',
  },
  matchTeamRole: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  vsBadgeContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 12,
  },
  vsBadgeSmall: {
    fontSize: 10,
    fontWeight: '800',
    color: '#9CA3AF',
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  detailItem: {
    width: '45%',
  },
  detailLabel: {
    fontSize: 11,
    color: '#9CA3AF',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  detailValue: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2937',
  },
  venueName: {
    fontSize: 17,
    fontWeight: '700',
    color: '#06392e',
  },
  venueLocation: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 4,
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  timeText: {
    fontSize: 13,
    color: '#4B5563',
    fontWeight: '500',
  },
  officialsGroup: {
    gap: 10,
  },
  officialCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    backgroundColor: '#F9FAF7',
    borderRadius: 12,
  },
  officialAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F0FDF4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  officialInitial: {
    fontSize: 16,
    fontWeight: '700',
    color: '#15803D',
  },
  officialNamePremium: {
    fontSize: 15,
    fontWeight: '600',
    color: '#06392e',
  },
  officialRolePremium: {
    fontSize: 11,
    color: '#6B7280',
  },
  modalFooterPremium: {
    padding: 20,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  closeBtnFooter: {
    backgroundColor: '#01b854',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
  },
  closeBtnFooterText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  dismissalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  dismissalTile: {
    width: '31%',
    aspectRatio: 1.3,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 2,
  },
  dismissalTileActive: {
    backgroundColor: '#06392e',
    borderColor: '#06392e',
  },
  dismissalIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  dismissalIconContainerActive: {
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  dismissalText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4B5563',
    textAlign: 'center',
  },
  dismissalTextActive: {
    color: '#FFFFFF',
  },
  batterSelectionTile: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  batterSelectionTileActive: {
    backgroundColor: '#06392e',
    borderColor: '#06392e',
  },
  batterSelectionName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#374151',
    marginTop: 10,
  },
  batterSelectionRole: {
    fontSize: 11,
    color: '#6B7280',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  playerGridTile: {
    width: '47%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 10,
  },
  playerGridTileActive: {
    backgroundColor: '#F0F9FF',
    borderColor: '#01b854',
  },
  playerGridName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
    flex: 1,
  },
  extraRunTile: {
    width: '30%',
    aspectRatio: 1.2,
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  extraRunTileActive: {
    backgroundColor: '#01b854',
    borderColor: '#01b854',
  },
  extraRunTileText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1F2937',
  },
  extraRunTileTextActive: {
    color: '#FFFFFF',
  },
  wagonWheelContainer: {
    padding: 20,
    alignItems: 'center',
    flex: 1,
  },
  groundOuter: {
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: '#059669',
    borderWidth: 4,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    position: 'relative',
    overflow: 'hidden',
  },
  groundInner: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  pitchCenter: {
    width: 20,
    height: 40,
    backgroundColor: '#FDE68A',
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -10,
    marginTop: -20,
    borderRadius: 2,
    zIndex: 10,
    borderWidth: 1,
    borderColor: '#dcc093'
  },
  dividerLine: {
    position: 'absolute',
    width: 1.5,
    height: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    left: '50%',
    marginLeft: -0.75,
  },
  region: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  regionLabel: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10
  },
  longOff: { bottom: 35, left: 45, width: 80, height: 60 },
  longOn: { bottom: 35, right: 45, width: 80, height: 60 },
  cover: { bottom: 105, left: 10, width: 80, height: 60 },
  midWicket: { bottom: 105, right: 10, width: 80, height: 60 },
  point: { top: 95, left: 10, width: 80, height: 60 },
  squareLeg: { top: 95, right: 10, width: 80, height: 60 },
  thirdMan: { top: 35, left: 45, width: 80, height: 60 },
  fineLeg: { top: 35, right: 45, width: 80, height: 60 },
  skipBtn: {
    marginTop: 40,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
  },
  skipBtnText: {
    color: '#6B7280',
    fontWeight: '600',
  },
  container: { flex: 1, backgroundColor: '#F3F4F6' },
  tabsStickyWrapper: { backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E7EB', zIndex: 10 },
  tabsInnerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  titleWrapper: { paddingHorizontal: 24, borderLeftWidth: 1, borderLeftColor: '#E5E7EB', height: '100%', justifyContent: 'center' },
  heroLabel: { fontSize: 12, fontWeight: '800', color: '#01b854', textTransform: 'uppercase', letterSpacing: 1.5 },
  tabsScroll: { paddingHorizontal: 24, paddingVertical: 16, gap: 12 },
  tab: { paddingHorizontal: 16, paddingVertical: 12, marginRight: 16, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabActive: { borderBottomColor: '#B91C1C' },
  tabText: { fontSize: 15, fontWeight: '600', color: '#6B7280' },
  scoringTopNav: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
    backgroundColor: '#FFFFFF',
  },
  backNavBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  backNavBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  tabTextActive: { color: '#06392e', fontWeight: '800' },
  mainScroll: { flex: 1 },
  mainScrollContent: { paddingBottom: 60 },
  contentContainer: { flex: 1 },
  subTabContainer: { flexDirection: 'row', backgroundColor: '#E5E7EB', marginHorizontal: 20, marginTop: 20, borderRadius: 12, padding: 2, gap: 2 },
  subTab: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 10 },
  subTabActive: { backgroundColor: '#FFFFFF', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  subTabText: { fontSize: 14, fontWeight: '600', color: '#6B7280' },
  subTabTextActive: { color: '#06392e' },
  matchesList: { paddingHorizontal: 20, paddingTop: 0, paddingBottom: 20, gap: 12 },
  matchCard: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#E5E7EB' },
  matchHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, borderBottomWidth: 1, borderBottomColor: '#F3F4F6', paddingBottom: 12 },
  matchType: { fontSize: 14, fontWeight: '600', color: '#374151' },
  matchTournament: { color: '#9CA3AF', fontWeight: '400' },
  matchMeta: { fontSize: 12, color: '#6B7280', marginTop: 4 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  statusBadgeUpcoming: { backgroundColor: '#F1F5F9' },
  statusBadgeLive: { backgroundColor: '#F0FDF4', flexDirection: 'row', alignItems: 'center', gap: 6 },
  statusBadgeResult: { backgroundColor: '#F0F9FF' },
  statusBadgeText: { fontSize: 11, fontWeight: '700' },
  statusBadgeTextResult: { color: '#0369A1' },
  statusBadgeTextUpcoming: { color: '#64748B' },
  statusBadgeTextLive: { color: '#15803D' },
  matchTeams: { marginTop: 16, marginBottom: 8 },
  matchTeamRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  teamInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  teamNameText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2937',
  },
  teamScoreText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#06392e',
  },
  teamOversText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '400',
  },
  teamRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  teamName: { fontSize: 15, color: '#06392e' },
  teamNameBold: { fontWeight: '700', fontSize: 16 },
  teamScore: { fontSize: 14, color: '#4B5563' },
  teamScoreBold: { fontWeight: '700', color: '#06392e', fontSize: 16 },
  matchMessage: { fontSize: 13, color: '#4B5563', fontStyle: 'italic', marginBottom: 12, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#F3F4F6' },
  matchResultText: { fontSize: 13, color: '#059669', fontWeight: '600', marginBottom: 12 },
  matchFooter: { flexDirection: 'row', gap: 20, borderTopWidth: 1, borderTopColor: '#F3F4F6', paddingTop: 12 },
  footerLink: { fontSize: 13, color: '#01b854', fontWeight: '600' },
  pulseDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#4ADE80' },
  liveActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  liveActionBtnText: {
    color: '#01b854',
    fontSize: 14,
    fontWeight: '600',
  },
  tournamentCard: { backgroundColor: '#FFFFFF', borderRadius: 20, overflow: 'hidden', borderWidth: 1, borderColor: '#E5E7EB' },
  imageContainer: { height: 160, position: 'relative' },
  tournamentImage: { width: '100%', height: '100%' },
  imageOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.3)' },
  crownBadge: { position: 'absolute', top: 12, left: 12, width: 24, height: 24, borderRadius: 6, backgroundColor: '#B91C1C', alignItems: 'center', justifyContent: 'center' },
  ongoingBadge: { position: 'absolute', top: 12, right: 12, backgroundColor: '#B91C1C', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  ongoingBadgeText: { color: '#FFFFFF', fontSize: 10, fontWeight: '700' },
  tournamentTitleOverlay: { position: 'absolute', bottom: 12, left: 12, right: 12, color: '#FFFFFF', fontSize: 18, fontWeight: '800' },
  tournamentInfo: { padding: 16, flexDirection: 'row', alignItems: 'center' },
  tournamentMeta: { fontSize: 13, color: '#6B7280', marginBottom: 2 },
  followLink: { color: '#01b854', fontWeight: '700', fontSize: 14 },
  teamCard: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB' },
  teamAvatar: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#F3F4F6', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderWidth: 1, borderColor: '#E5E7EB' },
  teamImage: { width: '100%', height: '100%' },
  teamInitials: { fontSize: 20, fontWeight: '800', color: '#FFFFFF' },
  teamContent: { flex: 1, marginLeft: 16, flexDirection: 'row', alignItems: 'center' },
  teamTitle: { fontSize: 16, fontWeight: '700', color: '#06392e', marginBottom: 4 },
  teamMetaRow: { flexDirection: 'row', alignItems: 'center' },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metaLabel: { fontSize: 12, color: '#6B7280' },
  captainIcon: { width: 14, height: 14, borderRadius: 7, backgroundColor: '#6B7280', alignItems: 'center', justifyContent: 'center' },
  captainIconText: { color: '#FFFFFF', fontSize: 9, fontWeight: '900' },
  searchBarContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', marginHorizontal: 20, marginVertical: 16, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, borderWidth: 1, borderColor: '#E5E7EB', gap: 10 },
  searchInput: { flex: 1, fontSize: 14, color: '#06392e', outlineStyle: 'none' as any },
  statsPromoHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#FFFFFF', paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  statsPromoText: { fontSize: 14, color: '#374151', fontWeight: '500' },
  analyzeBtn: { backgroundColor: '#dcc093', paddingHorizontal: 14, paddingVertical: 6, borderRadius: 99 },
  analyzeBtnText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  statsFilterBar: { flexDirection: 'row', paddingHorizontal: 20, paddingVertical: 16, gap: 10 },
  statPill: { paddingHorizontal: 18, paddingVertical: 8, borderRadius: 99, backgroundColor: '#E5E7EB' },
  statPillActive: { backgroundColor: '#dcc093' },
  statPillText: { fontSize: 13, fontWeight: '600', color: '#4B5563' },
  statPillTextActive: { color: '#FFFFFF' },
  statsContent: { paddingHorizontal: 20 },
  statsSectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  statsSectionTitle: { fontSize: 16, fontWeight: '700', color: '#06392e' },
  compareBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#01b854', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, gap: 6 },
  compareBtnText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  statTile: { width: '19%', backgroundColor: '#FFFFFF', paddingVertical: 12, alignItems: 'center', borderRadius: 8, borderWidth: 1, borderColor: '#E5E7EB' },
  statValue: { fontSize: 15, fontWeight: '800', color: '#06392e', marginBottom: 2 },
  statLabel: { fontSize: 10, color: '#9CA3AF', fontWeight: '500' },
  captainFooter: { marginTop: 10 },
  ballTypeLabel: { fontSize: 14, color: '#06392e', fontWeight: '600', marginBottom: 10 },
  adBanner: { marginVertical: 20, borderRadius: 20, overflow: 'hidden', height: 120, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5E7EB', position: 'relative' },
  adImage: { width: '100%', height: '100%', opacity: 0.6 },
  adOverlay: { ...StyleSheet.absoluteFillObject, padding: 20, justifyContent: 'center' },
  adTitle: { fontSize: 16, color: '#06392e', lineHeight: 20 },
  adTitleBold: { fontWeight: '900', fontSize: 20 },
  adBtn: { backgroundColor: '#01b854', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, alignSelf: 'flex-start', marginTop: 10 },
  adBtnText: { color: '#FFFFFF', fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  tabContent: { paddingVertical: 70, paddingHorizontal: 30, alignItems: 'center', justifyContent: 'center' },
  placeholderIconArea: { width: 100, height: 100, borderRadius: 50, backgroundColor: '#F0FDF4', alignItems: 'center', justifyContent: 'center', marginBottom: 24 },
  placeholderTitle: { fontSize: 26, fontWeight: '900', color: '#06392e', marginBottom: 12, textAlign: 'center' },
  placeholderDesc: { fontSize: 16, color: '#6B7280', textAlign: 'center', lineHeight: 26, maxWidth: 340, marginBottom: 32 },
  placeholderBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#043529', paddingHorizontal: 24, paddingVertical: 14, borderRadius: 16 },
  placeholderBtnText: { fontSize: 15, fontWeight: '800', color: '#FFFFFF' },
  plusIconWrapper: {
    paddingHorizontal: 24,
    borderLeftWidth: 1,
    borderLeftColor: '#E5E7EB',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  actionModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    width: '100%',
    maxWidth: 400,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#06392e',
  },
  modalOptions: {
    gap: 8,
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 16,
    backgroundColor: '#F9FAF7',
    gap: 16,
  },
  optionIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
  },
  modalDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: 8,
  },
  selectionView: {
    padding: 24,
    backgroundColor: '#FFFFFF',
    flex: 1,
    minHeight: 400,
    maxWidth: 600,
    alignSelf: 'center',
    width: '100%',
  },
  selectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 40,
  },
  cancelText: {
    fontSize: 16,
    color: '#6B7280',
    fontWeight: '600',
  },
  selectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#06392e',
  },
  teamSelectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 40,
  },
  teamSlot: {
    flex: 1,
    aspectRatio: 1,
    backgroundColor: '#F9FAF7',
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  teamSlotFilled: {
    borderStyle: 'solid',
    borderColor: '#01b854',
    backgroundColor: '#FFFFFF',
  },
  emptySlot: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  slotAction: {
    fontSize: 12,
    fontWeight: '700',
    color: '#01b854',
    textAlign: 'center',
  },
  vsContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#06392e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vsText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    width: '100%',
    maxWidth: 450,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.25,
    shadowRadius: 40,
    elevation: 25,
  },
  formGroup: {
    marginBottom: 20,
  },
  slotAvatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#F3F4F6',
    marginBottom: 12,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  slotImage: {
    width: '100%',
    height: '100%',
  },
  slotInitials: {
    fontSize: 24,
    fontWeight: '800',
    color: '#9CA3AF',
  },
  slotName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#06392e',
    textAlign: 'center',
  },
  startMatchBtn: {
    backgroundColor: '#01b854',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 20,
  },
  startMatchBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  selectBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  selectBtnText: {
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '700',
  },
  createTeamCard: {
    borderStyle: 'dashed',
    borderColor: '#01b854',
    backgroundColor: '#F0FDF4',
  },
  createTeamIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#01b854',
  },
  createTeamText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#01b854',
    marginBottom: 2,
  },
  createTeamSubtext: {
    fontSize: 13,
    color: '#6B7280',
  },
  createTeamModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    width: '100%',
    maxWidth: 450,
    padding: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 20,
  },
  formGroup: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: '#06392e',
    outlineStyle: 'none' as any,
  },
  submitBtn: {
    backgroundColor: '#01b854',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 10,
  },
  submitBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  qrModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    width: '100%',
    maxWidth: 450,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 30,
    elevation: 20,
  },
  qrBody: {
    alignItems: 'center',
  },
  qrCard: {
    width: '100%',
    backgroundColor: '#F9FAF7',
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
  },
  qrHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    alignSelf: 'flex-start',
    marginBottom: 24,
  },
  teamAvatarQr: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#01b854',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  teamInitialsQr: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 16,
  },
  qrTeamName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#06392e',
  },
  qrTeamMeta: {
    fontSize: 12,
    color: '#6B7280',
  },
  qrContainer: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    marginBottom: 20,
  },
  qrImage: {
    width: 180,
    height: 180,
  },
  qrFooterText: {
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 20,
  },
  downloadBtn: {
    marginTop: 24,
    width: '100%',
    backgroundColor: '#06392e',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
  },
  downloadBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  successModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    width: '90%',
    maxWidth: 380,
    padding: 32,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.2,
    shadowRadius: 40,
    elevation: 25,
  },
  successIconWrapper: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#01b854',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#06392e',
    marginBottom: 8,
  },
  successMessage: {
    fontSize: 15,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 28,
  },
  successCloseBtn: {
    backgroundColor: '#06392e',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 14,
    width: '100%',
    alignItems: 'center',
  },
  successCloseBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  loginBtnInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#01b854',
  },
  loginBtnTextInline: {
    fontSize: 14,
    fontWeight: '700',
    color: '#01b854',
  },
  addPlayerModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    width: '95%',
    maxWidth: 800,
    maxHeight: '92%',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.25,
    shadowRadius: 40,
    elevation: 25,
  },
  addPlayerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  activeTeamInfo: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  teamAvatarLarge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#01b854',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  teamInitialsLarge: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '800',
  },
  activeTeamName: {
    fontSize: 22,
    fontWeight: '800',
    color: '#06392e',
    marginBottom: 4,
  },
  activeTeamMeta: {
    fontSize: 14,
    color: '#6B7280',
  },
  divider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginHorizontal: -20,
    marginBottom: 24,
  },
  addPlayerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#06392e',
  },
  addPlayerScroll: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  sectionHeading: {
    fontSize: 16,
    fontWeight: '700',
    color: '#06392e',
    marginBottom: 20,
  },
  inviteContainer: {
    gap: 16,
    marginBottom: 10,
  },
  inviteLabelRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  inviteLabel: {
    fontSize: 15,
    color: '#374151',
    fontWeight: '600',
  },
  linkBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  linkIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#CCFBF1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  linkText: {
    flex: 1,
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
  },
  shareBtn: {
    backgroundColor: '#149D8F',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 10,
  },
  shareBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  manualOptionsContainer: {
    marginTop: 10,
  },
  manualOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 20,
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  optionCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionContent: {
    flex: 1,
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#06392e',
    marginBottom: 2,
  },
  optionSubtext: {
    fontSize: 12,
    color: '#6B7280',
  },
  assignAdminBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DCFCE7',
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 12,
  },
  adminBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#22C55E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminBadgeText: {
    fontSize: 12,
    color: '#22C55E',
    fontWeight: '700',
  },
  adminBannerText: {
    fontSize: 14,
    color: '#06392e',
  },
  promoBanner: {
    backgroundColor: '#149D8F',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginVertical: 1,
  },
  promoContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  promoIconPlaceholder: {
    width: 40,
    height: 30,
    backgroundColor: '#FFFFFF33',
    borderRadius: 4,
  },
  promoText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  squadSection: {
    backgroundColor: '#F9FAFB',
    minHeight: 100,
  },
  playerCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    gap: 16,
  },
  playerAvatar: {
    position: 'relative',
  },
  avatarCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  onlineDot: {
    position: 'absolute',
    top: 0,
    right: 4,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#dcc093',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  playerNameText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#374151',
  },
  squadFooter: {
    flexDirection: 'row',
    height: 60,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  footerTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#71717A',
  },
  footerTabActive: {
    backgroundColor: '#149D8F',
  },
  footerTabText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  footerTabTextActive: {
    fontWeight: '800',
  },
  profileHeader: {
    paddingTop: 60,
    paddingBottom: 24,
    paddingHorizontal: 16,
    backgroundColor: '#06392e',
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  profileHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 20,
    alignItems: 'center',
  },
  profileInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 24,
  },
  profileAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  profileAvatarText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
  },
  profileNameText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 2,
  },
  profileMetaText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    fontWeight: '500',
  },
  profileActionsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  rankBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    paddingVertical: 10,
    borderRadius: 8,
  },
  rankBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  insightsBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#149D8F',
    paddingVertical: 10,
    borderRadius: 8,
  },
  insightsBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  profileTabsFixed: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    paddingTop: 12,
  },
  profileSubTab: {
    paddingBottom: 12,
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  profileSubTabActive: {
    borderBottomColor: '#B91C1C',
  },
  profileSubTabText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  profileSubTabTextActive: {
    color: '#06392e',
    fontWeight: '800',
  },
  profilePlaceholder: {
    alignItems: 'center',
    paddingTop: 40,
  },
  placeholderImg: {
    width: 200,
    height: 150,
    borderRadius: 16,
    marginBottom: 24,
    opacity: 0.8,
  },
  placeholderTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#06392e',
    marginBottom: 8,
    textTransform: 'capitalize',
  },
  placeholderDesc: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
  },
  statsSummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statBox: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    alignItems: 'center',
  },
  statBoxValue: {
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 4,
  },
  statBoxLabel: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '600',
  },
  performanceChart: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  formCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trophyGrid: {
    flexDirection: 'row',
    gap: 16,
  },
  trophyBox: {
    flex: 1,
    backgroundColor: '#FAF9F6',
    padding: 24,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trophyYear: {
    fontSize: 12,
    color: '#dcc093',
    fontWeight: '800',
    marginTop: 12,
  },
  trophyEvent: {
    fontSize: 14,
    fontWeight: '700',
    color: '#06392e',
    textAlign: 'center',
    marginTop: 4,
  },
  leaderboardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    gap: 12,
  },
  rankNum: {
    fontSize: 16,
    fontWeight: '900',
    color: '#9CA3AF',
    width: 20,
  },
  miniAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#06392e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMemberSmallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 99,
  },
  addMemberSmallText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#01b854',
  },
  leaderboardSubTabs: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    padding: 3,
    marginBottom: 8,
  },
  lbSubTab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 6,
  },
  lbSubTabActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  lbSubTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
  },
  lbSubTabTextActive: {
    color: '#06392e',
    fontWeight: '700',
  },
  playerSelectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    gap: 16,
  },
  playerSelectRowActive: {
    borderColor: '#01b854',
    backgroundColor: '#F0FDF4',
  },
  checkBox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBoxActive: {
    backgroundColor: '#01b854',
    borderColor: '#01b854',
  },
  selectionSubTitle: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '600',
  },
  selectionFooter: {
    padding: 20,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  vsDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
    backgroundColor: '#F9FAFB',
    padding: 24,
    borderRadius: 20,
    marginBottom: 32,
  },
  vsTeam: {
    flex: 1,
    alignItems: 'center',
  },
  vsName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#06392e',
    textAlign: 'center',
  },
  vsPlayers: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 4,
  },
  vsBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  vsBadgeText: {
    fontSize: 14,
    fontWeight: '900',
    color: '#EF4444',
  },
  configLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 12,
  },
  typeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  typePill: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 99,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  typePillActive: {
    backgroundColor: '#F0FDF4',
    borderColor: '#01b854',
  },
  typePillText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  typePillTextActive: {
    color: '#01b854',
  },
  configInput: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    fontWeight: '600',
    color: '#06392e',
  },
  hundredInfo: {
    backgroundColor: '#fcf8ef',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFEDD5',
  },
  hundredText: {
    color: '#EA580C',
    fontWeight: '700',
    textAlign: 'center',
  },
  ballTypes: {
    flexDirection: 'row',
    gap: 12,
  },
  ballTypeBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
  },
  ballTypeBtnActive: {
    backgroundColor: '#06392e',
  },
  ballText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#6B7280',
  },
  decisionTextActive: {
    color: '#FFFFFF',
  },
  openerSection: {
    marginBottom: 32,
  },
  openerLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  playingXiLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#06392e',
    textTransform: 'uppercase',
  },
  playerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  playerGridTile: {
    width: '31.5%',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  playerGridTileActive: {
    backgroundColor: '#06392e',
    borderColor: '#06392e',
  },
  playerGridName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#374151',
    marginTop: 6,
    textAlign: 'center',
  },
  playerGridNameActive: {
    color: '#01b854',
  },
  warningText: {
    fontSize: 12,
    color: '#B91C1C',
    fontWeight: '700',
    backgroundColor: '#FEF2F2',
    padding: 10,
    borderRadius: 12,
    marginBottom: 12,
  },
  scoringContainer: {
    flex: 1,
  },
  scoringContentWrapper: {
    flex: 1,
    maxWidth: 1000,
    width: '100%',
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    // Platform-specific shadow/border would go here
  },
  mainScoreboard: {
    padding: 16,
    paddingTop: 12,
  },
  scoringTeamName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  bigRuns: {
    fontSize: 40,
    fontWeight: '900',
    color: '#06392e',
  },
  overText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#6B7280',
    marginBottom: 4,
  },
  scoreNumberRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  crrBadge: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    alignItems: 'center',
  },
  crrLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#6B7280',
  },
  crrValue: {
    fontSize: 18,
    fontWeight: '900',
    color: '#06392e',
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  targetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    marginBottom: 16,
  },
  targetText: {
    fontSize: 13,
    color: '#4B5563',
    fontWeight: '600',
    flex: 1,
  },
  playerStatsRow: {
    flexDirection: 'column',
    gap: 16,
    marginBottom: 16,
  },
  batsmanCol: {
    flex: 1.5,
  },
  bowlerCol: {
    flex: 1,
  },
  statsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    marginBottom: 8,
  },
  statsHeaderText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#9CA3AF',
    textTransform: 'uppercase',
  },
  statsHeadValues: {
    flexDirection: 'row',
    gap: 12,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  playerName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#374151',
    flex: 1,
  },
  statsValues: {
    flexDirection: 'row',
    gap: 12,
  },
  statsValueText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#06392e',
    width: 20,
    textAlign: 'center',
  },
  statsHeaderTextFixed: {
    fontSize: 10,
    fontWeight: '800',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    width: 22,
    textAlign: 'center',
  },
  statsValueTextFixed: {
    fontSize: 12,
    fontWeight: '700',
    color: '#06392e',
    width: 22,
    textAlign: 'center',
  },
  liveIndicatorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#01b854',
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 12,
  },
  modalSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 48,
    gap: 12,
  },
  modalSearchInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#06392e',
    // @ts-ignore
    outlineStyle: 'none',
  },
  manualEntryForm: {
    paddingTop: 16,
  },
  formLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#4B5563',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  addPlayerMiniActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#01b854',
    borderRadius: 12,
    paddingVertical: 14,
    marginTop: 24,
    gap: 8,
  },
  addPlayerMiniActionText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#01b854',
  },
  timelineContainer: {
    height: 48,
    justifyContent: 'center',
  },
  ballCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ballWicket: {
    backgroundColor: '#EF4444',
  },
  ballBoundary: {
    backgroundColor: '#01b854',
  },
  ballLabel: {
    fontSize: 12,
    fontWeight: '900',
    color: '#4B5563',
  },
  scoringWheel: {
    marginTop: 16,
    gap: 8,
  },
  wheelRow: {
    flexDirection: 'row',
    gap: 8,
  },
  runBtn: {
    flex: 1,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  runBtnText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#06392e',
  },
  boundaryBtn: {
    backgroundColor: '#F0FDF4',
    borderColor: '#01b854',
  },
  boundaryBtnText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#01b854',
  },
  wicketBtn: {
    backgroundColor: '#FEF2F2',
    borderColor: '#EF4444',
  },
  extraRow: {
    flexDirection: 'row',
    gap: 8,
  },
  extraBtn: {
    flex: 1,
    height: 44,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  extraBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#4B5563',
  },
  scoringActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  actionIconBtn: {
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 16,
    width: '22%',
  },
  actionIconText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6B7280',
    marginTop: 6,
  },
  contactItem: {
    width: 80,
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  playerTileActive: {
    backgroundColor: '#F0FDF4',
    borderColor: '#01b854',
    borderWidth: 2,
  },
  playerTileName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4B5563',
    marginTop: 8,
  },
  playerTileNameActive: {
    color: '#01b854',
  },
  contactItemFooter: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  startMatchMainBtn: {
    backgroundColor: '#06392e',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
  },
  startMatchMainBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  wagonWheelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    padding: 16,
    borderRadius: 16,
  },
  wagonWheelDesc: {
    fontSize: 14,
    color: '#06392e',
    fontWeight: '500',
  },
  toggleBg: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E5E7EB',
    padding: 4,
  },
  toggleBgActive: {
    backgroundColor: '#01b854',
  },
  toggleCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  toggleCircleActive: {
    transform: [{ translateX: 20 }],
  },
  pitchBtn: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  pitchBtnActive: {
    backgroundColor: '#F0FDF4',
    borderColor: '#01b854',
  },
  pitchText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  pitchTextActive: {
    color: '#01b854',
  },
  pickerWrapper: {
    position: 'relative',
  },
  pickerIcon: {
    position: 'absolute',
    right: 16,
    top: 18,
  },
  officialsTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 20,
    marginTop: 32,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  officialsTriggerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  officialIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  officialsTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#06392e',
  },
  officialsSub: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  officialGroupTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#06392e',
    marginBottom: 12,
  },
  officialInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  officialInput: {
    flex: 1,
    height: 52,
    fontSize: 15,
    fontWeight: '600',
    color: '#06392e',
  },
  officialValueText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#06392e',
    paddingVertical: 16,
  },
  officialPlaceholderText: {
    color: '#9CA3AF',
    fontWeight: '500',
  },
  officialResultCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    gap: 12,
  },
  resultName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#06392e',
  },
  resultPhone: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  resultRole: {
    fontSize: 12,
    fontWeight: '700',
    color: '#01b854',
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 99,
  },
  noResultArea: {
    alignItems: 'center',
    paddingTop: 40,
  },
  noResultTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#374151',
    marginTop: 16,
  },
  noResultSub: {
    fontSize: 14,
    color: '#9CA3AF',
    marginTop: 4,
    textAlign: 'center',
  },
  addNewOfficialBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 32,
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#DCFCE7',
  },
  addNewOfficialText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#01b854',
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    gap: 12,
  },
  contactAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactInitial: {
    color: '#01b854',
    fontWeight: '700',
    fontSize: 16,
  },
  contactName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#06392e',
  },
  contactPhone: {
    fontSize: 13,
    color: '#6B7280',
  },
  imagePickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  dashboardContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    padding: 24,
  },
  dashboardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
  },
  dashboardTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#0F172A',
  },
  matchesSection: {
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#334155',
    marginBottom: 20,
  },
  emptyMatches: {
    padding: 40,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
  },
  emptyMatchesText: {
    color: '#94A3B8',
    fontSize: 15,
  },
  teamGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 16,
  },
  teamItem: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
  },
  teamItemSelected: {
    borderColor: '#01b854',
    backgroundColor: '#F0FDF4',
  },
  teamName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#475569',
  },
  teamNameActive: {
    color: '#01b854',
  },
  confirmBtn: {
    backgroundColor: '#01b854',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: '#01b854',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  confirmBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  configFooter: {
    padding: 24,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  coin: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#FFD700',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    borderWidth: 4,
    borderColor: '#DAA520',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
  },
  coinFlipping: {
    transform: [{ scale: 1.2 }],
  },
  coinInner: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#FFD700',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#DAA520',
  },
  coinText: {
    fontSize: 48,
    fontWeight: '900',
    color: '#DAA520',
  },
  tapToFlipText: {
    marginTop: 20,
    fontSize: 14,
    color: '#64748B',
    fontWeight: '600',
  },
  tossWinnerSelection: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  tossTeamBtn: {
    flex: 1,
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
  },
  tossTeamBtnActive: {
    backgroundColor: '#F0FDF4',
    borderColor: '#01b854',
  },
  tossTeamName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#475569',
  },
  tossTeamNameActive: {
    color: '#01b854',
  },
  decisionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  decisionBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
  },
  decisionBtnActive: {
    backgroundColor: '#06392e',
    borderColor: '#06392e',
  },
  decisionText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#475569',
  },
  decisionTextActive: {
    color: '#FFFFFF',
  },
  imagePickerPlaceholder: {
    alignItems: 'center',
    gap: 4,
  },
  imagePickerText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  imagePickerPreview: {
    width: '100%',
    height: '100%',
  },
  removeImageBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#FEF2F2',
  },
  removeImageText: {
    color: '#EF4444',
    fontSize: 13,
    fontWeight: '600',
  },
  dropdownTrigger: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownValue: {
    fontSize: 15,
    color: '#06392e',
  },
  dropdownPlaceholder: {
    color: '#9CA3AF',
  },
  statesDropdown: {
    marginTop: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 5,
  },
  stateItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  stateItemText: {
    fontSize: 14,
    color: '#374151',
  },
  coin: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#dcc093',
    padding: 6,
    shadowColor: '#dcc093',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#D97706',
    alignItems: 'center',
    justifyContent: 'center',
  },
  coinInner: {
    width: '100%',
    height: '100%',
    borderRadius: 44,
    borderWidth: 2,
    borderColor: '#B45309',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D97706',
  },
  coinText: {
    fontSize: 40,
    fontWeight: '900',
    color: '#FEF3C7',
  },
  tapToFlipText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  tossWinnerSelection: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 12,
    width: '100%',
  },
  tossTeamBtn: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
  },
  tossTeamBtnActive: {
    borderColor: '#01b854',
    backgroundColor: '#F0FDF4',
    borderWidth: 2,
  },
  tossTeamName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4B5563',
    textAlign: 'center',
    marginTop: 8,
  },
  tossTeamNameActive: {
    color: '#065F46',
    fontWeight: '800',
  },
  decisionRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 12,
    width: '100%',
  },
  decisionBtn: {
    flex: 1,
    paddingVertical: 20,
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  decisionBtnActive: {
    backgroundColor: '#06392e',
    borderColor: '#06392e',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  decisionText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#6B7280',
  },
  decisionTextActive: {
    color: '#FFFFFF',
  },
  overSummaryBanner: {
    backgroundColor: '#06392e',
    padding: 20,
    marginHorizontal: 16,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  overSummaryText: {
    color: '#9CA3AF',
    fontSize: 14,
    fontWeight: '700',
  },
  scoreSummaryText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
  },
  filterBar: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    flexDirection: 'row',
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: '#06392e',
  },
  filterChipText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  filterChipTextActive: {
    color: '#FFFFFF',
  },
  settingsBtnSquare: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  drawerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  drawerContent: {
    width: '85%',
    maxWidth: 400,
    backgroundColor: '#FFFFFF',
    height: '100%',
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    shadowColor: '#000',
    shadowOffset: { width: -4, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 20,
  },
  drawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  drawerTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#06392e',
  },
  settingSection: {
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#F9FAFB',
  },
  sectionHeaderTextMenu: {
    fontSize: 16,
    fontWeight: '800',
    color: '#06392e',
  },
  sectionOptionsList: {
    backgroundColor: '#FFFFFF',
  },
  settingOptionRow: {
    paddingVertical: 18,
    paddingHorizontal: 32,
    borderBottomWidth: 1,
    borderBottomColor: '#F9FAF7',
  },
  settingOptionText: {
    fontSize: 15,
    color: '#374151',
    fontWeight: '600',
  },
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  sheetContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    maxHeight: '85%',
  },
  sheetHandle: {
    width: 48,
    height: 5,
    backgroundColor: '#E5E7EB',
    borderRadius: 3,
    alignSelf: 'center',
    marginBottom: 24,
  },
  sheetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
  },
  sheetGridItem: {
    width: '25%',
    alignItems: 'center',
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  sheetIconBox: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  sheetItemLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#4B5563',
    textAlign: 'center',
    lineHeight: 14,
  },
  showLessBtn: {
    alignItems: 'center',
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  showLessText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#01b854',
  },
  extraSelectorContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
  },
  extraSelectorTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#06392e',
    marginBottom: 4,
  },
  extraSelectorDesc: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 24,
  },
  extraRunsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 24,
  },
  extraRunTile: {
    width: 70,
    height: 70,
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  extraRunTileText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#06392e',
  },
  cancelExtraBtn: {
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  cancelExtraText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#6B7280',
  },
  sheetTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#06392e',
    fontFamily: 'Inter',
  },
  sheetSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
    marginTop: 6,
    fontFamily: 'Inter',
  },
  addPlayerMiniBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 16,
    backgroundColor: '#F0FDF4',
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#01b854',
    marginTop: 16,
    justifyContent: 'center',
  },
  addPlayerMiniText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#01b854',
  },
  tabsStickyWrapper: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    zIndex: 10,
  },
  tabsInnerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 8,
  },
  tabsScroll: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  tab: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginRight: 12,
    borderRadius: 12,
    backgroundColor: '#F9FAFB',
  },
  tabActive: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#01b854',
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  tabTextActive: {
    color: '#01b854',
    fontWeight: '800',
  },
  plusIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#DCFCE7',
  },
  mainScroll: {
    flex: 1,
  },
  mainScrollContent: {
    paddingBottom: 40,
  },
  actionModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    width: '90%',
    maxWidth: 400,
    padding: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.2,
    shadowRadius: 40,
    elevation: 25,
  },
  actionModalTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#06392e',
    textAlign: 'center',
    marginBottom: 32,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'space-between',
  },
  actionItem: {
    width: '47%',
    alignItems: 'center',
    marginBottom: 16,
  },
  actionIconBox: {
    width: 64,
    height: 64,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  actionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
    textAlign: 'center',
  },
  actionCloseBtn: {
    marginTop: 24,
    paddingVertical: 16,
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
    alignItems: 'center',
  },
  actionCloseBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#6B7280',
  },
  playerSelectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    gap: 12,
  },
  playerSelectRowActive: {
    backgroundColor: '#F0FDF4',
    borderColor: '#01b854',
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  playerNameText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#06392e',
  },
  checkBox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBoxActive: {
    backgroundColor: '#01b854',
    borderColor: '#01b854',
  },
  captainPickBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
  },
  captainPickBtnActive: {
    backgroundColor: '#06392e',
  },
  captainPickText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#6B7280',
    letterSpacing: 0.5,
  },
  captainPickTextActive: {
    color: '#01b854',
  },
  teamCardPremium: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  teamCardPremiumActive: {
    borderColor: '#01b854',
    backgroundColor: '#F0FDF4',
  },
  teamCardPremiumDisabled: {
    opacity: 0.6,
    backgroundColor: '#F9FAFB',
  },
  teamAvatarPremium: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  teamInitialsPremium: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  teamContentPremium: {
    flex: 1,
    marginLeft: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  teamTitlePremium: {
    fontSize: 16,
    fontWeight: '700',
    color: '#06392e',
    marginBottom: 6,
    fontFamily: 'Inter',
  },
  teamMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  metaBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6B7280',
    fontFamily: 'Inter',
  },
  selectBtnPremium: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
  },
  selectBtnPremiumActive: {
    backgroundColor: '#01b854',
  },
  selectBtnPremiumDisabled: {
    backgroundColor: '#E5E7EB',
  },
  selectBtnTextPremium: {
    fontSize: 13,
    fontWeight: '700',
    color: '#4B5563',
    fontFamily: 'Inter',
  },
  qrIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTabContainer: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    marginHorizontal: 24,
    marginTop: 8,
    marginBottom: 16,
    padding: 4,
    borderRadius: 14,
  },
  modalTabItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 10,
    borderRadius: 10,
  },
  modalTabItemActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  modalTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
    fontFamily: 'Inter',
  },
  modalTabTextActive: {
    color: '#06392e',
    fontWeight: '700',
  },
  closeBtnPremium: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#01b854',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
  },
  placeholderBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Inter',
  },
  scanQrActionBtn: {
    padding: 4,
  },
  scannedTeamResult: {
    marginHorizontal: 24,
    marginTop: 12,
    padding: 16,
    backgroundColor: '#F0FDF4',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#01b854',
    gap: 12,
  },
  scannedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  scannedTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#01b854',
    flex: 1,
  },
  fullModalScanner: {
    flex: 1,
    backgroundColor: '#000000',
  },
  scannerHeader: {
    position: 'absolute',
    top: 50,
    left: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 20,
  },
  scannerTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  scannerClose: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scannerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  scannerFrame: {
    width: 250,
    height: 250,
    borderWidth: 2,
    borderColor: '#01b854',
    borderRadius: 24,
    backgroundColor: 'transparent',
  },
  scannerHint: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 24,
    textAlign: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
  },
  vsSelectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
  },
  vsSelectionSide: {
    flex: 1,
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  vsSelectionSideActive: {
    backgroundColor: '#F8FAFC',
  },
  vsSelectionAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  vsSelectionInitial: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1E293B',
  },
  vsSelectionName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1E293B',
    textAlign: 'center',
  },
  vsSelectionRole: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94A3B8',
    letterSpacing: 1,
  },
  vsBadgeContainerLarge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#FFFFFF',
    zIndex: 10,
    marginHorizontal: -12,
  },
  vsBadgeTextLarge: {
    fontSize: 14,
    fontWeight: '900',
    color: '#64748B',
  },
  selectionGuideBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#ECFDF5',
    padding: 16,
    borderRadius: 16,
    marginTop: 24,
  },
  selectionGuideText: {
    flex: 1,
    fontSize: 13,
    color: '#065F46',
    lineHeight: 18,
  },
  teamPickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  teamAvatarSmall: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  teamInitialSmall: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
  },
  teamPickerName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
  },
  teamPickerLoc: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 48,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    color: '#1E293B',
  },
  scanQrBtnSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#ECFDF5',
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#10B981',
  },
  scanQrBtnTextSmall: {
    fontSize: 14,
    fontWeight: '600',
    color: '#01b854',
  },
  playerSelectRowPremium: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  playerSelectRowPremiumActive: {
    borderColor: '#01b854',
    backgroundColor: '#F0FDF4',
  },
  checkBoxPremium: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBoxPremiumActive: {
    backgroundColor: '#01b854',
    borderColor: '#01b854',
  },
  playerNamePremium: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1E293B',
  },
  playerNamePremiumActive: {
    color: '#059669',
  },
  playerRolePremium: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  captainBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
  },
  captainBtnActive: {
    backgroundColor: '#ECFDF5',
  },
  captainLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#01b854',
  },
  selectionSubTitleSmall: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  emptyMembersBox: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyMembersText: {
    color: '#94A3B8',
    textAlign: 'center',
  },
});

export { styles };
